import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const rubik = Rubik({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "900"],
  variable: "--font-rubik", // Specify the weights you want to include
});

export const metadata: Metadata = {
  title: "Gym Template By Wael Nasser",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-gray-200">
      <body
        className={`${rubik.variable} w-full max-w-[1920px] mx-auto bg-white`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
